/**
 * Cloudflare Stream utilities — server-side only.
 *
 * Required environment variables:
 *   CLOUDFLARE_ACCOUNT_ID          — from Cloudflare dashboard → Account Home → right panel
 *   CLOUDFLARE_STREAM_API_TOKEN    — API token with Stream:Edit permission
 *   CLOUDFLARE_STREAM_SIGNING_KEY  — (optional) for signed playback URLs on Pro-gated lessons
 *
 * Docs: https://developers.cloudflare.com/stream/
 */

const CF_BASE = "https://api.cloudflare.com/client/v4/accounts";

function accountId(): string {
  const id = process.env.CLOUDFLARE_ACCOUNT_ID;
  if (!id) throw new Error("CLOUDFLARE_ACCOUNT_ID is not configured.");
  return id;
}

function apiToken(): string {
  const token = process.env.CLOUDFLARE_STREAM_API_TOKEN;
  if (!token) throw new Error("CLOUDFLARE_STREAM_API_TOKEN is not configured.");
  return token;
}

function cfHeaders() {
  return {
    Authorization: `Bearer ${apiToken()}`,
    "Content-Type": "application/json",
  };
}

// ── Types ────────────────────────────────────────────────────────────────────

export type VideoStatus = "queued" | "inprogress" | "ready" | "error";

export type VideoDetails = {
  videoId: string;
  status: VideoStatus;
  /** HLS manifest URL for playback */
  playbackUrl: string | null;
  /** Thumbnail image URL (auto-generated by CF) */
  thumbnailUrl: string | null;
  /** Duration in seconds (available once ready) */
  durationSeconds: number | null;
  /** Whether transcoding is complete */
  ready: boolean;
};

export type DirectUploadResult = {
  /** One-time TUS upload URL — pass this to the browser */
  uploadUrl: string;
  /** Cloudflare video UID — store on the lesson immediately */
  videoId: string;
};

// ── API calls ────────────────────────────────────────────────────────────────

/**
 * Create a one-time direct-upload URL.
 * The browser uses this URL with the TUS protocol to upload directly to
 * Cloudflare without the file passing through your server.
 */
export async function createDirectUpload(
  maxDurationSeconds = 7200,
): Promise<DirectUploadResult> {
  const url = `${CF_BASE}/${accountId()}/stream/direct_upload`;
  const response = await fetch(url, {
    method: "POST",
    headers: cfHeaders(),
    body: JSON.stringify({ maxDurationSeconds, requireSignedURLs: true }),
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`Cloudflare Stream API error (${response.status}): ${text.slice(0, 400)}`);
  }

  type CFResult = { result: { uploadURL: string; uid: string } };
  const json = (await response.json()) as CFResult;
  return {
    uploadUrl: json.result.uploadURL,
    videoId: json.result.uid,
  };
}

/**
 * Fetch the current state of a video (status, playback URL, thumbnail).
 * Poll this after upload until status === "ready".
 */
export async function getVideoDetails(videoId: string): Promise<VideoDetails> {
  const url = `${CF_BASE}/${accountId()}/stream/${encodeURIComponent(videoId)}`;
  const response = await fetch(url, { headers: cfHeaders() });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`Cloudflare Stream API error (${response.status}): ${text.slice(0, 400)}`);
  }

  type CFVideo = {
    result: {
      uid: string;
      status: { state: string };
      playback?: { hls?: string; dash?: string };
      thumbnail?: string;
      duration?: number;
      readyToStream?: boolean;
    };
  };
  const json = (await response.json()) as CFVideo;
  const r = json.result;
  const state = r.status?.state ?? "queued";

  return {
    videoId: r.uid,
    status: (["queued", "inprogress", "ready", "error"].includes(state)
      ? state
      : "queued") as VideoStatus,
    playbackUrl: r.playback?.hls ?? null,
    thumbnailUrl: r.thumbnail ?? null,
    durationSeconds: typeof r.duration === "number" ? r.duration : null,
    ready: r.readyToStream === true || state === "ready",
  };
}

/**
 * Delete a video from Cloudflare Stream.
 * Call when a lesson is deleted or its video replaced.
 */
export async function deleteVideo(videoId: string): Promise<void> {
  const url = `${CF_BASE}/${accountId()}/stream/${encodeURIComponent(videoId)}`;
  await fetch(url, { method: "DELETE", headers: cfHeaders() });
}

/**
 * Build the iframe embed URL for playback (no signing required for public lessons).
 * Use for free / public lessons.
 */
export function getPublicIframeUrl(videoId: string): string {
  return `https://iframe.cloudflarestream.com/${encodeURIComponent(videoId)}`;
}

export async function createSignedStreamToken(videoId: string, expiresInSeconds = 3600): Promise<string> {
  const ttl = Math.max(60, Math.min(expiresInSeconds, 24 * 60 * 60));
  const url = `${CF_BASE}/${accountId()}/stream/${encodeURIComponent(videoId)}/token`;
  const response = await fetch(url, {
    method: "POST",
    headers: cfHeaders(),
    body: JSON.stringify({
      exp: Math.floor(Date.now() / 1000) + ttl,
      downloadable: false,
    }),
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`Cloudflare Stream token error (${response.status}): ${text.slice(0, 400)}`);
  }

  type CFTokenResult = { result?: { token?: string } };
  const json = (await response.json()) as CFTokenResult;
  const token = json.result?.token;
  if (!token) throw new Error("Cloudflare Stream did not return a signed token.");
  return token;
}

export function getSignedIframeUrl(token: string): string {
  return `https://iframe.cloudflarestream.com/${encodeURIComponent(token)}`;
}

/**
 * Return true if Cloudflare Stream is configured in the environment.
 * Used to conditionally show the upload UI.
 */
export function isCloudflareStreamConfigured(): boolean {
  return Boolean(process.env.CLOUDFLARE_ACCOUNT_ID && process.env.CLOUDFLARE_STREAM_API_TOKEN);
}
